### ISSUE TITLE
Testing: Canada English and French site testing

### ISSUE THREAD

**Issue by Meli-lazarte** [aemsites/volvotrucks-na#290]
### Description
Updates have been applied to the US site, but these changes may not have been replicated on the Canada site (English and French versions). We need to test and compare the Canada sites in both languages against the US site to identify discrepancies and ensure consistency. The goal is to document any missing updates related to content.

### Tasks

- Test the Canada sites (English and French versions) against the US site.
- Identify discrepancies 

### Links
https://www.volvotrucks.ca/en-ca/
https://www.volvotrucks.ca/fr-ca/

**Comment by silviulungu** [comment]
1. Missing the search button on "en-ca" and "fr-ca". Present on "us"

<img width="1709" alt="Image" src="https://github.com/user-attachments/assets/8135b606-614e-4699-ac7b-cea1c14febcd" />

<img width="1721" alt="Image" src="https://github.com/user-attachments/assets/563b3c3d-4904-4c69-b274-a05ca27cbf93" />

2. Missing "l-Torque" category from the mega menu on "Trucks" section for "us" and "fr-ca". Present on "en-ca".

<img width="1298" alt="Image" src="https://github.com/user-attachments/assets/56da1ee5-d8c4-4fee-bcaa-f175c8bbc2b6" />

<img width="1434" alt="Image" src="https://github.com/user-attachments/assets/b18105d2-6f6d-49fe-b76c-b73865b8475e" />

3. Missing "My truck app" and "Premium Tech Tool / Workshop Toolbox" categories from the mega menu on "Services" section for "en-ca" and "fr-ca". Present on "us".

<img width="1293" alt="Image" src="https://github.com/user-attachments/assets/16e268ff-6b14-4b0b-ab3c-a6bb9d7d06c8" />

<img width="1304" alt="Image" src="https://github.com/user-attachments/assets/fc48dcd6-ea30-4753-bc98-1ff57518719e" />

4. Missing "Media Library" category from the mega menu on "News and Stories" section for "en-ca" and "fr-ca". Present on "us".

<img width="1303" alt="Image" src="https://github.com/user-attachments/assets/5199ee89-e8e3-476e-8491-2b4f64818108" />

<img width="1298" alt="Image" src="https://github.com/user-attachments/assets/a3fcaebd-59d8-4e75-a908-e6a96e26110f" />

5. This page is entirely wrong https://www.volvotrucks.ca/fr-ca/trucks/vnr-electric/. Missing sub-navigation, missing content, wrong style for key-facts block.
6. Missing "Overview" tab from sub-navigation. https://www.volvotrucks.ca/en-ca/trucks/vnl/
7. Wrong display of the video in v2 hero block on "en-ca" and "fr-ca".

<img width="1721" alt="Image" src="https://github.com/user-attachments/assets/8ce3bf98-f3d3-4e42-bf9f-4240d8b8ff31" />

<img width="1724" alt="Image" src="https://github.com/user-attachments/assets/f464198c-74bc-4c33-911b-52b1c0353cf5" />

8. Missing page https://www.volvotrucks.ca/en-ca/about-volvo/history/
9. Missing page https://www.volvotrucks.ca/fr-ca/parts-and-services/fleets/volvo-connect
10. Empty page https://www.volvotrucks.ca/fr-ca/purchasing-a-truck/inventory-search/
11. A lot of pages on "fr-ca" are on english.

**Comment by Meli-lazarte** [comment]
@Kannan-CM @Varunvolvo @rishav8597 can you take a look at this ticket and Silviu's comments? Thanks!

**Comment by Meli-lazarte** [comment]
This ticket will spillover with 2 SP.

**Comment by Varunvolvo** [comment]
Work in progress!!

**Comment by Varunvolvo** [comment]
1. Missing the search button on "en-ca" and "fr-ca". Present on "us"
- Fixed

2. Missing "l-Torque" category from the mega menu on "Trucks" section for "us" and "fr-ca". Present on "en-ca".
- Removed from all the sites now. 

3. Missing "My truck app" and "Premium Tech Tool / Workshop Toolbox" categories from the mega menu on "Services" section for "en-ca" and "fr-ca". Present on "us".
- Not required for Canada (en-ca and fr-ca)

4. Missing "Media Library" category from the mega menu on "News and Stories" section for "en-ca" and "fr-ca". Present on "us".
- Added 

5. This page is entirely wrong https://www.volvotrucks.ca/fr-ca/trucks/vnr-electric/. Missing sub-navigation, missing content, wrong style for key-facts block.
- The new VNR page is sent for translation review for Volvo team, We already have a teams ticket for this internally.

6. Missing "Overview" tab from sub-navigation. https://www.volvotrucks.ca/en-ca/trucks/vnl/
- Fixed

7. Wrong display of the video in v2 hero block on "en-ca" and "fr-ca".
- Fixed

8. Missing page https://www.volvotrucks.ca/en-ca/about-volvo/history/
- Fixed

9. Missing page https://www.volvotrucks.ca/fr-ca/parts-and-services/fleets/volvo-connect
- Page not required

10. Empty page https://www.volvotrucks.ca/fr-ca/purchasing-a-truck/inventory-search/
- Page is now removed and added the redirect 

11. A lot of pages on "fr-ca" are on English.
- We are already working on this task. We have a teams ticket for this internally.

**Comment by silviulungu** [comment]
The video for V2 Hero Block still not displayed.
<img width="1722" alt="Image" src="https://github.com/user-attachments/assets/650505bd-dbe0-41ee-86bd-2a2ecfb4c07f" />

Besides this and the pages that needs to be translated, everything else is fixed. Also i noticed an inconsistency on sub-navigation. I would like to know if content team have a "map" for sub-navigation, a "map" that displays what sub-navigation should show after clicking one option from it.

Example number 1:
If we click on "Service Contracts", all options on sub-navigation are changing except "Service Contracts".

<img width="1722" alt="Image" src="https://github.com/user-attachments/assets/6fe223b8-2563-457a-ab30-b2961f94fffc" />

<img width="1726" alt="Image" src="https://github.com/user-attachments/assets/001a8a73-728c-441e-b2cc-c23d8b936754" />

Example number 2:
If we click on "Warranty" the whole sub-navigation is gone.

<img width="1722" alt="Image" src="https://github.com/user-attachments/assets/a591d6b9-6fe7-4127-8797-6e9985d1db5f" />

<img width="1720" alt="Image" src="https://github.com/user-attachments/assets/13f4b7d2-a0b2-46b0-95c0-170c4412502b" />

**Comment by Kannan-CM** [comment]
HI @silviulungu,

The sub-navigation changes based on the section you click.
These are working as expected.

Here is the link to the Excel file where each sub-nav is mapped:
https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B305B2C8C-8E5C-488B-A83F-8ED01DFE825F%7D&file=metadata.xlsx&action=default&mobileredirect=true

**Comment by Varunvolvo** [comment]
The video is fixed - https://www.volvotrucks.ca/fr-ca/trucks/vnl/

**Comment by silviulungu** [comment]
This ticket will be closed as completed since the translation of the pages for fr-ca will take some time and dragging the ticket from sprint to sprint, until translation is ready, is not a good practice. 

Another ticket will be opened with this issue, when the content team is done.
